# Generated by Django 2.2 on 2020-10-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0002_auto_20201014_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_num',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
