# Generated by Django 2.2 on 2020-11-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_foodtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='typenames',
            new_name='typename',
        ),
    ]
