# Generated by Django 2.2 on 2020-11-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='childidname',
            new_name='childcidname',
        ),
    ]
