# Generated by Django 2.2 on 2020-10-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0002_student_s_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
