# Generated by Django 2.2 on 2020-10-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
