# Generated by Django 2.2 on 2020-10-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Two', '0005_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=16, unique=True)),
                ('s_password', models.CharField(max_length=128)),
                ('s_token', models.CharField(default=None, max_length=256)),
            ],
        ),
    ]
