# Generated by Django 2.2 on 2020-10-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='g_grade',
            new_name='g_name',
        ),
    ]
